version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: amazon/aws-sam-cli-emulation-image-nodejs12.x
    # image: node:lts
    container_name: line-bot
    tty: true
    volumes:
      - ./:/src
    working_dir: "/src"
    # command: /bin/bash -c "while sleep 1000; do :; done"

    